apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
    spec:
      containers:
      - name: orderapi-container
        image: microservice.azurecr.io/orderapi:latest
        ports:
        - containerPort: 6003
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: orderapi-service
spec:
  type: LoadBalancer
  selector:
    app: orderapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productapi
  template:
    metadata:
      labels:
        app: productapi
    spec:
      containers:
      - name: productapi-container
        image: microservice.azurecr.io/productapi:latest
        ports:
        - containerPort: 80
        - containerPort: 6001
---
apiVersion: v1
kind: Service
metadata:
  name: productapi-service
spec:
  type: LoadBalancer
  selector:
    app: productapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: searchapi
  template:
    metadata:
      labels:
        app: searchapi
    spec:
      containers:
      - name: searchapi-container
        image: microservice.azurecr.io/searchapi:latest 
        env:
        - name: Services__Products
          value: http://productapi-service
        - name: Services__Customers
          value: http://customerapi-service
        - name: Services__Orders
          value: http://orderapi-service
        ports:
        - containerPort: 80
        - containerPort: 6004
---
apiVersion: v1
kind: Service
metadata:
  name: searchapi-service
spec:
  type: LoadBalancer
  selector:
    app: searchapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi-container
        image: microservice.azurecr.io/customerapi:latest
        ports:
        - containerPort: 80
        - containerPort: 6002
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi-service
spec:
  type: LoadBalancer
  selector:
    app: customerapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
