version: '3.8'

services:
  mssql:
    image: custom-sql-search
    build: 
      context: ./sql-scripts
      dockerfile: dockerfile
    container_name: sqlServer
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AchalParashar@2024
    ports:
      - 1433:1433
    volumes:
      - sql_data:/var/opt/mssql  # Mount the volume to the SQL Server data directory

volumes:
  sql_data:
    driver: local  # Use the local driver for the volume

   