version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlServer
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AchalParashar@2024
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
      - ./sql-scripts:/sql-scripts
      #- ./entrypoint.sh:/entrypoint.sh
    #entrypoint: ["/bin/bash", "/entrypoint.sh"]

volumes:
  mssql-data:
