FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY "ECommerce.Api.Orders.csproj" .
RUN dotnet restore "ECommerce.Api.Orders.csproj"
COPY . .
RUN dotnet publish  -c Release -o /app/publish


FROM build  AS final
COPY --from=build /app/publish  .
ENTRYPOINT ["dotnet", "ECommerce.Api.Orders.dll"]

