# Use the official Microsoft SQL Server image as a base
FROM mcr.microsoft.com/mssql/server:2019-latest

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=AchalParashar@2024

# Copy the setup script to the container
COPY setup.sql /usr/src/app/setup.sql

# Run the setup script
RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 30 \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P AchalParashar@2024 -i /usr/src/app/setup.sql \
    && pkill sqlservr
